### ISSUE TITLE
link is invalid

### ISSUE THREAD

**Issue by Mdahao** [fcakir/mihash#8]
The link is invalid. i can not  download such as CIFAR10_VGG16_fc7.mat ,Places205_AlexNet_fc7_PCA128.mat and LabelMe_GIST.mat

**Comment by fatihcakirs** [comment]
Hi @mypython3, checking it, will update soon.

**Comment by fcakir** [comment]
Hi @mypython3 , checking the files, will update soon.

**Comment by kunhe** [comment]
Hi @mypython3 the links should be restored now. 
In the future we will move them to a more permanent place.
